language: php

env:
    global:
        - CC_TEST_REPORTER_ID=dee9b4d616e4b99d166eec47ada9e8a6cd1bbbd74c5b4604a6912b6f8ec004ec

jobs:
    include:
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: nightly
          env: COMPOSER_FLAGS="--ignore-platform-reqs"

before_script:
    - composer update $COMPOSER_FLAGS --no-interaction
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
